owner: xnaas
repo: asak-status

sites:
  - name: Homepage
    url: https://actionsack.com
    icon: https://raw.githubusercontent.com/xnaas/actionsack.com/master/src/docs/logo.png
  - name: IRC
    check: "tcp-ping"
    url: chat.actionsack.com
    port: 6697
    icon: https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/160/microsoft/209/speech-balloon_1f4ac.png
  - name: Mumble
    check: "tcp-ping"
    url: chat.actionsack.com
    port: 46304
    icon: https://www.mumble.info/favicon.ico
#  - name: Bibliogram
#    url: https://bib.actionsack.com
#    icon: https://bib.actionsack.com/favicon.ico
  - name: Nitter
    url: https://nitter.actionsack.com
    icon: https://raw.githubusercontent.com/zedeus/nitter/master/public/favicon.ico
  - name: OpenTogetherTube
    url: https://ott.actionsack.com
    icon: https://raw.githubusercontent.com/dyc3/opentogethertube/master/client/public/favicon.ico
  - name: rimgu
    url: https://i.actionsack.com/favicon.ico
    icon: https://imgur.com/favicon.ico
  - name: RSS-Bridge 🔒
    url: https://$ASAK_LOGIN@rss.actionsack.com
    icon: https://raw.githubusercontent.com/RSS-Bridge/rss-bridge/master/static/favicon.png
  - name: Send
    url: https://send.actionsack.com
    icon: https://raw.githubusercontent.com/timvisee/send/master/assets/favicon-32x32.png
  - name: youtube-dl
    url: https://ytdl.actionsack.com
    icon: https://www.youtube.com/favicon.ico
  - name: Download 🔒
    url: https://$ASAK_LOGIN@dl.actionsack.com
    icon: https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/160/whatsapp/314/floppy-disk_1f4be.png
  - name: Meme Wiki
    url: https://srsbznz.actionsack.com
    icon: https://raw.githubusercontent.com/splitbrain/dokuwiki/master/data/media/wiki/dokuwiki-128.png

status-website:
  cname: status.actionsack.com
  logoUrl: https://actionsack.com/logo.png
  favicon: https://actionsack.com/favicon.ico
  name: asak-status
  introMessage: Status monitoring for Action Sack services.
  navbar:
    - title: Status
      href: /
    - title: actionsack.com
      href: https://actionsack.com
  theme: dark
