# Change these first
owner: xnaas
repo: status-asak

sites:
  - name: Main
    url: https://actionsack.com
  - name: Bibliogram
    url: https://bib.actionsack.com
  - name: IRC
    check: "tcp-ping"
    url: chat.actionsack.com
    port: 6697
  - name: Mumble
    check: "tcp-ping"
    url: chat.actionsack.com
    port: 46304
  - name: Nitter
    url: https://nitter.actionsack.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /status-asak
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: status-asak
  introTitle: "Action Sack"
  introMessage: Status monitoring for ASAK services.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: ASAK
      href: https://actionsack.com
  theme: dark
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
