owner: xnaas
repo: asak-status

sites:
  - name: Homepage
    url: https://actionsack.com
  - name: Bibliogram
    url: https://bib.actionsack.com
  - name: IRC
    check: "tcp-ping"
    url: chat.actionsack.com
    port: 6697
    icon: https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/160/microsoft/209/speech-balloon_1f4ac.png
  - name: Mumble
    check: "tcp-ping"
    url: chat.actionsack.com
    port: 46304
    icon: https://www.mumble.info/favicon.ico
  - name: Nitter
    url: https://nitter.actionsack.com
  - name: rss-bridge
    url: https://rss.actionsack.com
    expectedStatusCodes:
      - 401
      - 403
    icon: https://raw.githubusercontent.com/RSS-Bridge/rss-bridge/master/static/favicon.png
  - name: youtube-dl
    url: https://ytdl.actionsack.com
    icon: https://www.youtube.com/favicon.ico

status-website:
  cname: status.actionsack.com
  logoUrl: https://actionsack.com/logo.png
  favicon: https://actionsack.com/favicon.ico
  name: asak-status
  introMessage: Status monitoring for Action Sack services.
  navbar:
    - title: Status
      href: /
    - title: actionsack.com
      href: https://actionsack.com
  theme: dark
