# Change these first
owner: xnaas
repo: status-asak

sites:
  - name: Homepage
    url: https://actionsack.com
  - name: Bibliogram
    url: https://bib.actionsack.com
  - name: IRC
    check: "tcp-ping"
    url: chat.actionsack.com
    port: 6697
    icon: https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/160/microsoft/209/speech-balloon_1f4ac.png
  - name: Mumble
    check: "tcp-ping"
    url: chat.actionsack.com
    port: 46304
    icon: https://www.mumble.info/favicon.ico
  - name: Nitter
    url: https://nitter.actionsack.com
  - name: rss-bridge
    url: https://rss.actionsack.com
    expectedStatusCodes:
      - 401
      - 403
    icon: https://raw.githubusercontent.com/RSS-Bridge/rss-bridge/master/static/favicon.png
  - name: youtube-dl
    url: https://ytdl.actionsack.com
    icon: https://www.youtube.com/favicon.ico

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /status-asak
  logoUrl: https://actionsack.com/avatar.png
  favicon: https://actionsack.com/favicon.ico
  name: status-asak
  # introTitle: "Action Sack Status"
  introMessage: Status monitoring for Action Sack services.
  navbar:
    - title: Status
      href: /status-asak/
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Homepage
      href: https://actionsack.com
  theme: dark
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
